import type { Metadata } from 'next'
import { Inter, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
// import Link from "next/link";
// import Transition from "@/components/Transition";

const inter = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${geistMono.variable} min-w-[320px] antialiased`}
      >
        <div
          id='header'
          className='absolute left-0 right-0 top-0 z-50 pb-4 pt-8 lg:relative lg:py-[6.5px]'
        >
          <div className='max-md:mx-5 md:mx-auto md:w-[87.5%]'>
            <Link
              href='/'
              autoFocus
              className='inline-block -translate-x-3 outline-none'
              style={{ textShadow: 'rgb(255 255 255 / 60%) 0px 0px 10px' }}
            >
              <span className='inline-block origin-bottom-right scale-[.8] text-4xl font-extralight leading-[1] tracking-tight'>
                STA
              </span>
              <span className='ml-px inline-block text-4xl font-medium leading-[1]'>
                tv
              </span>
            </Link>
          </div>
        </div>
        {/* <main className="relative overflow-x-hidden"> */}
        {/* <nav className="absolute top-0 left-0 right-0">
            <ul className="flex space-x-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
            </ul>
          </nav> */}
        {/* <Transition>{children}</Transition> */}
        {children}
        {/* </main> */}
      </body>
    </html>
  )
}
