import type { Metadata } from 'next'
import { Inter, Geist_Mono } from 'next/font/google'
import './globals.css'
import ButtonLink from '@/components/Button/Link'
// import Transition from "@/components/Transition";

const inter = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${geistMono.variable} min-w-[320px] antialiased`}
      >
        <div
          id='header'
          className='absolute left-0 right-0 z-50 before:table after:table max-lg:text-white max-md:top-0 lg:relative'
        >
          <div className='mt-3 max-md:mx-4 md:mx-auto md:w-[var(--max-width)] lg:my-[6.5px]'>
            <ButtonLink
              href='/'
              className='inline-block -translate-x-2 px-2 pb-1 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-400'
              style={{ textShadow: 'rgb(255 255 255 / 60%) 0px 0px 10px' }}
            >
              <span className='inline-block text-[27px] font-extralight leading-[1] tracking-tight'>
                STA
              </span>
              <span className='ml-px inline-block text-4xl font-medium leading-[1]'>
                tv
              </span>
            </ButtonLink>
          </div>
        </div>
        {/* <main className="relative overflow-x-hidden"> */}
        {/* <nav className="absolute top-0 left-0 right-0">
            <ul className="flex space-x-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
            </ul>
          </nav> */}
        {/* <Transition>{children}</Transition> */}
        {children}
        {/* </main> */}
      </body>
    </html>
  )
}
